version: "3.7"
services:
  video_compresser_service:
    build: .
    volumes:
      - /tmp/uploads:/tmp/uploads
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "1GB"
